export const REQUEST_MARKET_CAP_TABLE = 'REQUEST_MARKET_CAP_TABLE';
export const SUCCESS_MARKET_CAP_TABLE = 'SUCCESS_MARKET_CAP_TABLE';
export const FAILURE_MARKET_CAP_TABLE = 'FAILURE_MARKET_CAP_TABLE';


export const REQUEST_MARKET_CAP_DUSTRIBUTION = 'REQUEST_MARKET_CAP_DUSTRIBUTION';
export const SUCCESS_MARKET_CAP_DUSTRIBUTION = 'SUCCESS_MARKET_CAP_DUSTRIBUTION';
export const FAILURE_MARKET_CAP_DUSTRIBUTION = 'FAILURE_MARKET_CAP_DUSTRIBUTION';


export const REQUEST_MARKET_CAP_GLOBAL = 'REQUEST_MARKET_CAP_GLOBAL';
export const SUCCESS_MARKET_CAP_GLOBAL = 'SUCCESS_MARKET_CAP_GLOBAL';
export const FAILURE_MARKET_CAP_GLOBAL = 'FAILURE_MARKET_CAP_GLOBAL';
